package alexeyby.corsys.model.type;

public enum InjuryType {
	NO_INJURIES, AFTER_SURGERY, BONE_FRACTURE, SEPSIS, PERITONITIS,
	POLYTRAUMA_REHABILITATION, POLYTRAUMA_SEPSIS, MODERATE_BURNS,
	SEVERE_BURNS, VERY_SEVERE_BURNS
}