package alexeyby.corsys.model.type;

public enum NutritionalStatusType {
	NORMAL, OVERWEIGHT, OBESITY_CLASS_ONE, OBESITY_CLASS_TWO, OBESITY_CLASS_THREE,
	OBESITY_CLASS_FOUR, UNDERWEIGHT, HYPOTROPHY_CLASS_ONE, HYPOTROPHY_CLASS_TWO,
	HYPOTROPHY_CLASS_THREE
}
